bpo-15526: test_startfile changes the cwd (#1537)
Try to fix test_startfile's inability to clean up after itself in
time. Patch by Jeremy Kloth.

Fix the following support.rmtree() error while trying to remove the
temporary working directory used by Python tests:

WindowsError: [Error 32] The process cannot access the file because
it is being used by another process: ...

OriGinal commit: 8a53dbeb7a9d0ae3e446f36e56cf9acfabe443c1